### ISSUE TITLE
It is easy :)

### ISSUE THREAD

**Issue by tsdye** [joeroe/stratigraphr#1]
I don't know the R graph packages well, but you'll want to use one that is able to check for cycles.  I browsed ggraph and didn't see anything there, but igraph will run this check.  I believe that is what @nevrome was getting at in the thread with @zachbatist when he mentioned the logic check.

Also, if you decide to push forward with this, please consider the data structures set out by Dye and Buck (2015) and used in [hm](http://www.tsdye.online/harris-matrix/data-tables/).  The idea there was to have hm read csv files generated by SQL queries.

**Comment by joeroe** [comment]
Thanks @tsdye. I'm using `tidygraph` and `ggraph` as convenient wrappers, but the workhorse behind both is `igraph`, so yes hopefully verifying the topology will be easy.

I'll certainly look (again) at the way hm structures the data. If I recall correctly it's very compatible with the "tidy" approach used in modern R, so that should work well. The idea is not to compete with packages like hm or ArkMatrix, just to provide a version for those of us that are stuck in R ways!

**Comment by tsdye** [comment]
Ah, good to know about the tidyverse wrappers.  Thanks.

Competition is good!  In any event, you can be fairly certain your good ideas in stratigraphr will make their way into hm some day :)

**Comment by joeroe** [comment]
Basic validation was indeed easy. Input formats and data structures perhaps requires more thought: #2
